Add Gin Icon
LelouchFR/skill-icons pull request #308
Opened 2024-12-27 10:21 UTC by dingyuqi

# Add New Icon(s)

## Icon Details

| Icon ID   | Icon                                                                                          |
| --------- | --------------------------------------------------------------------------------------------- |
| gin-auto  | ![gin-auto](https://github.com/user-attachments/assets/ec5bf8e5-0e08-457e-b8f1-7074b8ae261b)  |
| gin-dark  | ![gin-dark](https://github.com/user-attachments/assets/5f591f60-a931-47af-a163-cf86372e375b)  |
| gin-light | ![gin-light](https://github.com/user-attachments/assets/b5f56f87-e049-49ae-b106-c4f280b17f12) |

## Notes
[Gin](https://gin-gonic.com/) is a web framework build for go. I get the icon from [gin-gonic/logo](https://github.com/gin-gonic/logo) repo and use the color icon in it.

I don't know how to check if the auto switch works correctly, but I referred to other people's pull requests. I hope it works well.

## Checklist
- [x] Added icon(s) to the appropriate directory
- [x] Updated documentation with the new icon(s)
- [x] Verified the icon(s) display correctly
- [ ] If the icon has light and dark, verified the auto switch works correctly
- [x] The Svg does not contain any sort of strokes

2024-12-27 10:44 UTC, LelouchFR commented
@dingyuqi why modify `.gitattributes` ?

2024-12-27 10:46 UTC, LelouchFR requested changes
Icon has a `#1E1E1E` background

The dark icon has a little problem... it doesn't look right.

2024-12-27 11:03 UTC, LelouchFR commented
for the dark icon, add this one:

```svg
<svg width="256" height="256" viewBox="0 0 256 256" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M196 0H60C26.8629 0 0 26.8629 0 60V196C0 229.137 26.8629 256 60 256H196C229.137 256 256 229.137 256 196V60C256 26.8629 229.137 0 196 0Z" fill="#242938"/>
<g clip-path="url(#clip0_842_20)">
<path d="M203.471 73.7561C194.912 106.709 172.902 125.748 136.983 132.17C106.413 122.766 106.413 125.518 101.293 117.414C132.55 93.6352 162.432 62.4403 176.57 26.2756C190.632 41.7202 195.141 44.9314 203.471 73.7561Z" fill="#F4F2ED"/>
<path d="M127.181 235.824C109.373 235.063 96.9912 232.692 87.1097 228.157C85.6675 227.495 85.8839 227.938 84.3282 222.459C81.619 212.919 79.5597 204.276 77.3537 193.183C76.2354 187.561 75.7116 185.21 73.1291 174.222C68.4949 154.505 66.7349 145.439 65.7222 136.069C65.4657 133.696 65.9275 130.452 66.6529 129.529C67.0824 128.983 67.0911 127.588 66.6658 127.477C66.4176 127.412 66.3561 127.202 66.2653 126.113C66.19 125.208 66.0727 124.716 65.8707 124.459C65.6759 124.211 65.5833 123.846 65.5833 123.324C65.5833 122.901 65.5145 122.512 65.4305 122.46C65.3386 122.403 65.2776 121.365 65.2776 119.86C65.2776 118.355 65.2166 117.317 65.1248 117.261C65.0407 117.209 64.9719 117.304 64.9719 117.472C64.9719 119.357 63.6179 115.924 62.8287 112.038C60.8032 102.065 57.4789 92.155 58.2437 98.3694C58.5127 100.556 59.0085 102.705 60.4319 107.856C62.104 113.908 62.8657 118.193 62.5257 119.634C62.0397 121.693 58.8994 109.325 57.0895 98.2226C56.6302 95.4051 55.9405 91.1732 55.5569 88.8183C54.6997 83.5563 53.9024 79.6048 52.813 75.2193C51.7225 70.8297 51.7534 70.1177 53.1085 68.3911C55.9018 64.8323 64.0986 62.0654 64.9847 64.3824C65.592 65.9705 63.8021 67.0707 58.9345 68.101C54.7157 68.9939 54.3255 69.6325 56.6157 71.8952C58.9054 74.1574 72.1859 76.1794 87.899 76.6581C115.729 77.5057 133.372 77.7288 138.339 77.296C139.558 77.1899 141.291 77.0628 142.19 77.0137C143.825 76.9247 143.825 76.9247 143.75 76.5255C143.694 76.223 143.824 75.9406 144.287 75.3616C144.624 74.9411 145.125 74.2874 145.403 73.9089C146.345 72.6215 147.929 72.1308 148.586 72.9225C149.407 73.9129 148.681 76.2053 147.324 76.9075C146.697 77.2318 146.877 77.3317 148.324 77.4623C149.011 77.5242 149.967 77.6165 150.448 77.6673C151.905 77.821 153.015 77.2947 152.403 76.7405C151.055 75.5199 153.592 73.058 157.521 71.7741C158.109 71.5817 158.656 71.3641 158.736 71.2904C158.816 71.2167 158.99 71.1565 159.123 71.1565C159.624 71.1565 161.058 70.0444 162.653 68.4196C163.56 67.4949 164.579 66.5636 164.917 66.35C165.255 66.1365 165.606 65.823 165.697 65.6536C165.972 65.1398 165.436 65.2782 164.246 66.0287C163.658 66.3998 162.832 66.9136 162.412 67.1707C161.539 67.7042 159.597 68.9924 157.729 70.2769C157.026 70.7604 156.279 71.2725 156.069 71.415C155.859 71.5574 155.562 71.7787 155.409 71.9067C155.071 72.1902 153.503 72.2582 152.63 72.0273C150.363 71.4276 150.2 69.4368 152.135 65.9795C152.982 64.4658 155.316 61.3698 155.61 61.3698C155.683 61.3698 155.937 61.0825 156.173 60.7312C156.602 60.0957 156.873 59.8904 158.237 59.1707C159.218 58.6531 159.791 58.5968 159.946 59.0028C160.039 59.244 159.352 60.7574 158.577 62.0176C156.954 64.6589 156.813 64.9276 156.964 65.0793C157.181 65.2959 158.833 64.304 159.078 63.8104C159.181 63.6035 159.456 63.0232 159.688 62.5207C161.265 59.122 165.038 58.7874 167.359 61.8403C167.972 62.6473 168.143 62.7387 168.146 62.2618C168.157 60.7695 170.234 59.5449 172.767 59.5374C173.818 59.5342 173.887 59.3623 172.977 59.0149C171.734 58.5398 171.663 58.3023 172.482 57.3649C173.618 56.0656 173.079 55.8132 170.921 56.6336C168.838 57.4252 166.814 57.8538 165.43 57.7962C164.695 57.7656 163.928 57.8024 163.726 57.8781C163.524 57.9537 162.985 58.0474 162.528 58.0864C162.071 58.1252 161.642 58.1915 161.574 58.2335C161.506 58.2756 161.116 58.2644 160.708 58.2086C158.44 57.8988 158.65 55.9311 161.491 50.8951C161.871 50.2222 162.394 49.2245 162.655 48.6778C162.916 48.1311 163.975 45.9635 165.009 43.8609C166.042 41.7583 167.172 39.4187 167.52 38.6618C167.867 37.9048 168.321 36.9586 168.529 36.559C168.738 36.1595 168.908 35.7635 168.908 35.679C168.908 35.5946 169.084 35.1645 169.299 34.7234C170.689 31.876 172.905 24.8472 172.635 24.1433C172.58 24.0005 172.626 23.9054 172.75 23.9054C172.863 23.9054 173.3 23.6759 173.721 23.3956C174.142 23.1152 174.674 22.7707 174.903 22.6301C175.245 22.4203 175.304 22.2966 175.233 21.9416C174.839 19.9693 178.479 21.23 183.008 24.6343C189.671 29.6419 195.586 38.1039 200.528 49.6994C204.921 60.0049 206.073 77.4824 203.225 90.5768C201.228 99.757 199.869 113.845 198.409 140.504C197.479 157.477 196.948 165.136 196.181 172.616C195.974 174.635 195.703 177.662 195.579 179.345C194.957 187.79 194.019 195.63 192.424 205.723C191.878 209.172 191.802 209.983 191.76 212.757C191.603 223.213 187.772 229.152 180.506 230.198C179.801 230.301 178.331 230.646 177.238 230.968C168.38 233.569 158.929 234.949 145.981 235.531C135.48 236.003 132.443 236.05 127.181 235.824ZM91.1081 220.008C89.2224 212.316 88.1193 208.665 86.7929 205.723C85.3731 202.573 85.0504 202.157 85.2259 203.696C86.032 210.776 87.9747 217.344 91.1368 223.676C92.8042 227.015 92.8035 226.924 91.1081 220.008ZM87.8026 225.105C88.353 223.05 87.4729 218.728 84.9101 210.902C83.4483 206.438 82.371 202.556 82.1682 201.02C82.0352 200.014 81.897 199.929 81.3249 200.502C80.4071 201.42 80.6847 203.32 82.7515 210.27C83.3077 212.14 83.8414 214.274 83.9377 215.011C84.5032 219.341 87.3528 226.784 87.8026 225.105ZM139.63 202.332C142.419 200.484 142.053 195.096 139.022 193.379C136.293 191.833 134.827 195.202 135.986 200.358C136.506 202.672 137.943 203.45 139.63 202.332ZM131.409 201.924C133.488 200.858 134.179 197.298 132.876 194.362C131.591 191.468 129.014 192.934 128.55 196.824C128.482 197.387 128.324 198.508 128.197 199.315C127.743 202.21 128.946 203.187 131.409 201.924ZM80.801 196.603C81.1343 193.933 80.4429 190.075 78.2058 182.126C77.5712 179.871 76.8395 176.945 76.5798 175.627C75.7306 171.313 74.445 169.211 75.0658 173.151C75.3673 175.064 77.0688 183.793 77.4356 185.308C77.6392 186.149 77.9831 188.27 78.2 190.023C78.7398 194.385 79.2134 196.113 80.1447 197.121C80.6063 197.62 80.6813 197.561 80.801 196.603ZM116.175 181.848C127.818 179.178 131.573 164.612 122.383 157.762C116.458 153.346 112.747 153.025 103.489 156.128C101.598 156.762 99.8951 157.379 99.7054 157.498C99.0308 157.923 97.9871 159.429 97.987 159.978C97.987 160.259 97.7169 161.16 97.3869 161.979C93.0138 172.83 104.148 184.605 116.175 181.848ZM101.426 173.511C96.8458 172.827 95.8587 168.925 99.3644 165.363C101.911 162.776 104.876 162.551 107.053 164.782C111.361 169.196 107.951 174.486 101.426 173.511ZM159.498 179.702C167.495 178.358 172.51 169.16 169.212 161.884C161.49 144.845 133.756 153.03 139.838 170.553C142.439 178.045 149.582 181.369 159.498 179.702ZM143.918 172.631C140.353 171.753 139.196 168.494 141.107 164.708C143.495 159.975 148.605 160.031 151.126 164.818C152.649 167.709 152.303 168.672 149.834 168.423C147.613 168.199 146.885 168.517 147.97 169.236C148.761 169.759 149.773 170.671 149.968 171.036C150.578 172.176 146.468 173.26 143.918 172.631ZM106.335 109.411C106.933 109.324 107.357 109.118 108.133 108.539C108.691 108.121 109.578 107.465 110.102 107.08C114.83 103.609 116.35 102.392 118.086 100.693C118.675 100.117 120.394 98.5651 121.908 97.2444C123.421 95.9237 124.941 94.5885 125.286 94.2774C125.632 93.9662 126.251 93.4134 126.662 93.0491C127.953 91.9059 130.238 89.8159 131.995 88.1717C134.058 86.2418 138.516 81.7308 138.485 81.6051C138.411 81.305 137.096 81.0539 135.511 81.0373C133.865 81.0198 133.83 81.012 133.842 80.672C133.859 80.2106 133.878 80.2131 129.397 80.1095C93.5515 79.2815 69.5325 78.0449 56.5508 76.3591C55.0389 76.1628 54.884 76.1675 54.884 76.4105C54.884 76.8358 56.1216 78.0118 57.0998 78.5163C58.3307 79.1511 58.3492 79.4292 57.1749 79.6433C55.916 79.8728 55.9539 79.724 56.4482 82.4912C58.4311 93.5923 61.3461 96.1053 67.5002 92.0186C71.0395 89.6683 93.7189 87.2339 108.686 87.5978C111.255 87.6602 113.027 87.6336 [...]

2024-12-30 01:08 UTC, dingyuqi commented
> @dingyuqi why modify `.gitattributes` ?

I modified the local `.gitattribute` file due to CRLF problems, but mistakenly committed the changes on the first commit. The second commit is to undo it.

2024-12-30 02:23 UTC, dingyuqi commented
I made a new commit. I hope the problem is solved.

2024-12-30 15:35 UTC, LelouchFR commented
@dingyuqi did you use the icons I gave you ?

normally you can just take the one I gave you and it's all good.

For the README file, did you use the script ? (it's situated at `.github/readme-format.sh`)

(for the icons, what are you using to make them ? and what OS are you using ?)

2024-12-31 01:28 UTC, dingyuqi commented
> @dingyuqi did you use the icons I gave you ?
> 
> normally you can just take the one I gave you and it's all good.
> 
> For the README file, did you use the script ? (it's situated at `.github/readme-format.sh`)
> 
> (for the icons, what are you using to make them ? and what OS are you using ?)

I copied the svg code and pasted it in Figma and exported it. I also used the `readme-format.sh` to update the README.md. I saw it has added gin logo in the table already.

This is the first time make the svg icon, and I may have made some mistakes. You can check my [repo commit records](https://github.com/dingyuqi/skill-icons/commits/main/) for possible problems. Thanks for your patience and help.

2025-01-16 07:28 UTC, LelouchFR commented
> I copied the svg code and pasted it in Figma and exported it.

@dingyuqi To make an icon, instead of exporting it, you only have to do right-click > copy as > copy as svg. (**but not for the xxx-auto.svg icon**)

To make the PR pass, just copy and paste the icons I've given you last time in their respective file without passing through figma, thank you. You should also resolve the conflics with the README.md file (optional, I can do it afterwards the Icon is good).

2025-01-16 08:15 UTC, closed without merging